### ISSUE TITLE
Update RubyGems

### ISSUE THREAD

**Issue by esurdam** [mchicote/capistrano3-autoscaling-deploy#2]
Howdy!

This gem available via RubyGems is outdated as compared to the latest master branch. As such certain tasks are breaking! Source works fine.

**Comment by marcoschicote** [comment]
Updated to version 1.5 with your contributions :)
https://rubygems.org/gems/capistrano3-autoscaling-deploy/versions/1.5

**Comment by esurdam** [comment]
Cheers! Thanks for maintaining :)
