### ISSUE TITLE
Attribute public IP address at the deploy for the auto scale instances

### ISSUE THREAD

**Issue by tryvin** [mchicote/capistrano3-autoscaling-deploy#5]
Hey there,

So, what about if the auto scale instances doesn't have a public IP address? By default amazon blocks all outgoing requests if you don't have a IP, this would block the git update, and so on.

What about this:

* Create a new allocation IP for VPC or Classical
* Allocate this IP with the instance
* Deploy
* Remove allocation

**Comment by marcoschicote** [comment]
Hi @tryvin 
Are requests also blocked when using public DNS name? If that's not the case you could just follow that path. 
If that it the case, your idea makes sense but I'm not sure if this gem should be responsible for something like that. Shouldn't another gem be in charge of such task?

**Comment by jacobrastad** [comment]
Hi @tryvin ,

If you don't have public IP's to your instances you can attach a NAT-gateway to you VPC.

By doing this your instances can send outgoing requests (as long as you don't block them in security groups etc).

Your suggestion would work too but I agree with @marcoschicote that those steps should be handled outside this gem.

**Comment by marcoschicote** [comment]
Closing this as there has not been activity for quite some time.
