### ISSUE TITLE
Create and Attach an AMI after deploy

### ISSUE THREAD

**Issue by frederikspang** [mchicote/capistrano3-autoscaling-deploy#6]
When you're deploying a new version to say X different servers. If your autoscaling-group adds another server, the group should be using an existing image.

I'm currently using the gem below, however I'm quite interested in the `primary` and `:db` functionality. (Also I'm unsure of it's maintenance)

I'd love to add a PR, if you're planning on keeping this maintained. I'll see if I can get the time sometime soon, if you haven't gotten around to it yet ;)

See [this gem](https://github.com/lserman/capistrano-elbas)

**Comment by marcoschicote** [comment]
Hi @frederikspang 
I'm not currently working on adding new functionality to this gem but if this would be something you would be interested and are willing to send a PR, I'll gladly review it and merge it.

**Comment by frederikspang** [comment]
I'll keep the issue open and hopefully get the time to make a PR sometime soon then!

**Comment by marcoschicote** [comment]
Closing this as there has not been activity for quite some time.
